[package]
name = "kaeru"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap =  { version = "4.5.21", features = ["cargo", "derive"] }
dirs = "5.0.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
toml = "0.8.19"
